version: "3.1"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: jardim4565
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"